title: Basic Machine Learning
twist: Not
url: https://basicml.com
resume: mailto:pankesh.bamotra@gmail.com
author: Pankesh Bamotra
email:
google_analytics: UA-49727693-11

profession: Machine learning scientist
description: Throwing "whats" at machine learning
keywords: machine learning, python, deep learning, computer vision, beginners, advanced, natural language processing, nlp, 深度 学习, 自然 语言 处理, pytorch, tensorflow, keras, artificial intelligence

# social links
github_username: pbamotra
linkedin_username: pbamotra
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
#  - tags.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-picture-tag
 - jekyll-mentions
 - jekyll-gist
 - jekyll-sitemap
 - jekyll-paginate
 - jekyll-inline-svg

markdown: kramdown

kramdown:
  math_engine: mathjax

jekyll-mentions:
  base_url: https://twitter.com

scholar:
  style: mla

paginate: 5
paginate_path: "/page/:num/"

svg:
  optimize: true
