# Site settings
title: Pankesh Bamotra
subtitle: "Data Scientist, Coupang USA"

description: > # this means to ignore newlines until "baseurl:"
  I am a data scientist and I work on image classification, visual search, 
  and object detection to detect structured information.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.pankesh.com" # the base hostname & protocol for your site
relative_permalinks: false

keywords: tutorial, machine learning, python, deep learning, computer vision, मशीन लर्निंग, natural language processing, 深度 学习, 自然 语言 处理, artificial intelligence

include: ["_assets", "_posts", "_pages", "_artworks"]

social:
  github: pbamotra
  medium: pbamotra

avatar: "_assets/pankesh-style-cpng.png"
disqus_short_name : 

contacts:
  email: <i>firstname</i>.<i>lastname</i>@gmail.com
  postal:
    address1:
    address2:
    street:
    zip:
    city: Redmond, Washington
  phone:
  pubkey:

cv_file: _assets/Pankesh___Resume.pdf
publist_file:
tags: tutorial, machine learning, python, deep learning, computer vision, मशीन लर्निंग, natural language processing, 深度 学习, 自然 语言 处理, artificial intelligence

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-paginate
  - jekyll-stickyposts
  - jekyll-inline-svg

stickyposts:
  # enabled: false   # Enable StickyPosts; default: true
  # debug: true      # Show additional info; default: false
  # sort: "date"      # Optional sort field; default: "date", use "none" to avoid sorting
  # reverse: false     # Ascending order, default: false
  retain: false      # Also show sticky posts in their original positions; default: false
  # reverse_sticky: true    # Reverse the order of the sticky posts, e.g. oldest first; default: false

paginate: 5
paginate_path: "/blog/page/:num/"